language: php

php:
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - composer install
  - pear install PHP_CodeSniffer
  - phpenv rehash

script:
  - phpunit AllTests tests/TechDivision/PBC/AllTests.php
