language: php

php:
  - "5.5"
  - "5.4"

before_script:
  - pear install PHP_CodeSniffer
  - pecl install xdebug
  - phpenv rehash
  - wget https://scrutinizer-ci.com/ocular.phar

script:
  - ant phpcs
  - ant run-tests
  - php ocular.phar code-coverage:upload --format=php-clover $TRAVIS_BUILD_DIR/target/reports/unit/coverage/clover.xml