language: php

php:
  - "5.5"
  - "5.4"

before_script:
  - pear install PHP_CodeSniffer
  - phpenv rehash
  - phpcs --report=summary -pn .
  - composer install

script:
  - phpunit AllTests tests/TechDivision/PBC/Tests/AllTests.php
