language: php

php:
  - "5.5"
  - "5.4"

before_script:
  - composer install
  - pear install PHP_CodeSniffer
  - phpenv rehash
  
script:
  - phpcs --report=summary --standard=PSR2 --ignore=*/vendor/* -pn .
  - phpunit AllTests tests/TechDivision/PBC/Tests/AllTests.php
